"use client"

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import { ThemeProvider } from "next-themes";
import Header from "@/components/header";
import Footer from "@/components/footer";
import { usePathname } from "next/navigation";
import Particles from "@/components/blocks/Backgrounds/Particles/Particles";

import 'leaflet/dist/leaflet.css';


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pathname = usePathname();
  const loginPortal = pathname === "/login" || pathname === "/register";
  console.log("pathname", pathname);

  return (
    <html lang="en" suppressHydrationWarning>
      
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased font-sans`}
      >
        {!loginPortal && <Header className="mt-2" />}
        
        <ThemeProvider attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange >

          <div className="fixed inset-0 -z-10 w-full min-h-screen">
             <Particles
    particleColors={['#dc2626', '#f97316']}
    particleCount={200}
    particleSpread={10}
    speed={0.1}
    particleBaseSize={100}
    moveParticlesOnHover={true}
    alphaParticles={false}
    disableRotation={false}
  />
          </div>

          <div style={{ position: 'relative', minHeight: '100vh' }}>
            <main className="min-h-screen">{children}</main>
          </div>
          
        
        {!loginPortal && <Footer className=""/>}
        </ThemeProvider>
        
      </body>
    </html>
  );
}
